[1m[31mERROR   [0m test_flow:test_flow.py:188 Failed to handle 'Already Logged In' popup: Message: 
Stacktrace:
	GetHandleVerifier [0x0x7ff7f230e935+77845]
	GetHandleVerifier [0x0x7ff7f230e990+77936]
	(No symbol) [0x0x7ff7f20c9cda]
	(No symbol) [0x0x7ff7f21206aa]
	(No symbol) [0x0x7ff7f212095c]
	(No symbol) [0x0x7ff7f2173d07]
	(No symbol) [0x0x7ff7f214890f]
	(No symbol) [0x0x7ff7f2170b07]
	(No symbol) [0x0x7ff7f21486a3]
	(No symbol) [0x0x7ff7f2111791]
	(No symbol) [0x0x7ff7f2112523]
	GetHandleVerifier [0x0x7ff7f25e684d+3059501]
	GetHandleVerifier [0x0x7ff7f25e0c0d+3035885]
	GetHandleVerifier [0x0x7ff7f2600400+3164896]
	GetHandleVerifier [0x0x7ff7f2328c3e+185118]
	GetHandleVerifier [0x0x7ff7f233054f+216111]
	GetHandleVerifier [0x0x7ff7f23172e4+113092]
	GetHandleVerifier [0x0x7ff7f2317499+113529]
	GetHandleVerifier [0x0x7ff7f22fe298+10616]
	BaseThreadInitThunk [0x0x7ff840aa7374+20]
	RtlUserThreadStart [0x0x7ff8419dcc91+33]