[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C564FCA710>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/bc7c7b2eda5577c120b4fffe8f6f5f17/screenshot
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C565039810>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/bc7c7b2eda5577c120b4fffe8f6f5f17/screenshot
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C565039A70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/bc7c7b2eda5577c120b4fffe8f6f5f17/screenshot
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C564FEAAD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/bc7c7b2eda5577c120b4fffe8f6f5f17
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C564FEABE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/bc7c7b2eda5577c120b4fffe8f6f5f17
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C564FEAF10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/bc7c7b2eda5577c120b4fffe8f6f5f17